### ISSUE TITLE
Focusing last radio button and hitting down arrow key does not focus first radio button

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#18] opened 2020-05-06 23:56 UTC
## Describe the bug
When focused within a radio group, hitting the down arrow key when the last option is selected does nothing and throws a console error. Vanilla radio button groups will loop around and focus the first option in the group.

Markup used:
```html
<ods-inputoption-radio-group for="radio1" label="Form label goes here">
  <ods-inputoption id="radio1" label="Yes" name="radioDemo1" type="radio" value="yes"></ods-inputoption>
  <ods-inputoption id="radio2" label="No" name="radioDemo1" type="radio" value="no"></ods-inputoption>
  <ods-inputoption id="radio3" label="Maybe" name="radioDemo1" type="radio" value="maybe"></ods-inputoption>
</ods-inputoption-radio-group>
```

## To Reproduce
1. Render the above markup and open in a browser
2. Tab to select the first option
3. Hit the down arrow twice to focus the last option
4. Hit the down arrow one more time. Notice the first option is not selected and a console error is logged.

Error in Chrome:
```
Uncaught TypeError: Cannot read property 'renderRoot' of undefined
    at HTMLElement.value (npm.alaskaairux.6cd03a4eba6b8fb78dd2.bundle.js:1)
    at HTMLElement.value (npm.alaskaairux.6cd03a4eba6b8fb78dd2.bundle.js:1)
```

Error in Firefox:
```
TypeError: this._items[o] is undefined npm.alaskaairux.6cd03a4eba6b8fb78dd2.bundle.js:1:43955
    value http://localhost:8080/npm.alaskaairux.6cd03a4eba6b8fb78dd2.bundle.js:1
    value http://localhost:8080/npm.alaskaairux.6cd03a4eba6b8fb78dd2.bundle.js:1
```

## Expected behavior
When the last radio button in the group and the down arrow is hit, the first radio button in the group is focused.

## Environment
OS: Windows 10
Browser: Firefox 76/Chrome 81
Package version: 2.0.1

## Audit

https://github.com/AlaskaAirlines/auro_docs/issues/123

**Comment by blackfalcon** [comment] 2020-05-07 00:08
yes, this is an issue when you come to the end of the array. It is not a bug that impedes performance or causes an error, but the solution can be done better.

**Comment by blackfalcon** [comment] 2020-05-19 21:16
See https://github.com/AlaskaAirlines/ods-inputoptions/issues/10 for information about de-scoping. 

Closing this issue as ods-inputOptions is now deprecated.

**Closed as completed by blackfalcon** 2020-05-19 21:16 UTC
Labels: Type: Bug, Status: Work In Progress, Priority: High
