### ISSUE TITLE
Input Options (Checkboxes) IE11 Rendering Error

### ISSUE THREAD

**Issue by aaronluannguyen** [AlaskaAirlines/OrionStatelessComponents__ods-inputoptions#3] opened 2019-09-19 22:10 UTC
# Issue report

Your issue may already be reported! Please search on the issue tracker before creating one.

## Expected Behavior
Checkboxes should render on IE 

## Current Behavior
When running checkboxes on IE 11, window errors out with 
```Unhandled promise rejection TypeError: Unable to get property 'map' of undefined or null reference```
While debugging it seems to be coming from ```componentData.map()``` in the src code of this component.

## Possible Solution
Maybe use a traditional for loop instead of using modern js techniques of looping through an array

## Steps to Reproduce (for bugs)

1. https://preorderfood.azurewebsites.net/preorderfood?pnr=UMOSCS&lastName=Nguyen&numFlights=1#/menu/893-2019-09-24-SEA-HNL-UMOSCS
2. Click on a food item to attempt to open modal
3. Inspect element -> Console
4. Welcome to all the error goodies

## Context
Prevents IE 11 compatibility for Preorder Food Project

## Your Environment
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Dell Windows Laptop
* Link to your project: https://itsals.visualstudio.com/CustomerMobile/_git/MobileWeb on the ```reactPreorderFood``` branch

**Comment by geoffrich** [comment] 2019-11-14 18:05
I know it's been a while since this issue was opened, but I've researched it and wanted to provide some details/possible solutions for anyone else with this problem.

The issue is React-specific and has nothing to do with the call to `map`, which is [fully supported in IE11](http://kangax.github.io/compat-table/es5/#test-Array.prototype.map). I was able to render the inputoptions in IE11 outside of React and was also able to render the inputoptions in IE11 in Angular. The root cause is that componentData is not properly passed to the component in a React app rendered in IE11. My guess is that it has to do with React passing everything to custom elements as an attribute instead of a property (see [Custom Elements Everywhere](https://custom-elements-everywhere.com/#react)). In other browsers you can get around this by calling `JSON.stringify` on the array/object you want to pass down, but this doesn't work in IE11 for some reason (possibly because of the polyfills?).

If you need to support IE11 and are using the inputoptions inside a React app, you can get around this issue by using a ref. Below is a working example. It throws an exception in IE on first render, but re-renders once you set the componentData using the ref.

```
import React, { Component } from 'react';
import '@alaskaairux/orion-design-tokens/dist/tokens/CSSTokenProperties.css';
import "@alaskaairux/ods-inputoptions";

class App extends Component {
  componentData = [
    { "id": "radio1", "value": "yes", "label": "Yes" },
    { "id": "radio2", "value": "no", "label": "No" },
    { "id": "radio3", "value": "maybe", "label": "Maybe" }
  ];

  constructor(props) {
    super(props);
    this.inputOptionsRef = React.createRef();
  }

  render() {
    return (
      <ods-inputoptions
          ref={this.inputOptionsRef}
          id="rdo"
          type="radio"
          name="rdo"
          for="radio1" 
          componentData={JSON.stringify(this.componentData)}
      ></ods-inputoptions>
    );
  }

  componentDidMount() {
    this.inputOptionsRef.current.componentData = this.componentData;
  }
}

export default App;

```

A [refactor of the component is being considered](https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-inputoptions/issues/4) that would remove the componentData array in favor of rendering a component for each radio button/checkbox. This will indirectly solve this issue, since arrays and objects would no longer be used. However, any other components using arrays/objects in projects that need React IE11 support would still need to use the workaround.

Since there's a work around and the problem is both framework and browser specific, I will be closing the issue.

**Closed as completed by geoffrich** 2019-11-14 18:05 UTC
